### ISSUE TITLE
require is not a function error

### ISSUE THREAD

**Issue by doongzzi** [Neamar/heroku-self-ping#13]
require('heroku-self-ping')("http://your-app-url"); 
this usage omits "require" is not a function error. how can i solve it?..

**Comment by Neamar** [comment]
Hello,

Are you running `nodejs`?

`require` is a built-in function and should always be available for CommonJS files (`.js`).

**Comment by doongzzi** [comment]
yes i'm using app.js at express/nodeJS workframe.
To solve the problem i tried this way below. didn't omitted an error but i'm not sure if it will work.
const herokuping = require("heroku-self-ping").default(process.env.APP_URL);

**Comment by Neamar** [comment]
Yeah, OK I see. You're correct, I'll update the README!
